// Cláusulas por defecto de la Hoja de Recepción del taller.
// Fuente única de verdad: la consumen app/taller/recepcion/page.tsx (editor/preview)
// y app/api/pdf/recepcion/route.ts (PDF). Antes existían dos copias que ya habían
// divergido ("notifying" vs "notificando" y distinta garantía).
// La garantía oficial de reparación es de 12 meses (alineada con las cotizaciones).
export const CLAUSULAS_RECEPCION_DEFAULT = `1. DIAGNÓSTICO TÉCNICO: Todo equipo ingresado a las instalaciones de Bionordi S.A. de C.V. será sometido a un proceso de diagnóstico técnico especializado. Dicho diagnóstico tiene un costo de $1,500.00 MXN (más IVA), el cual es obligatorio e independiente de la decisión que tome el cliente respecto al servicio. En caso de que el cliente apruebe la reparación, el costo del diagnóstico quedará integrado dentro del presupuesto total, sin cargo adicional. El tiempo estimado para la emisión del diagnóstico es de 3 a 5 días hábiles contados a partir de la fecha de ingreso registrada en el presente documento. Bionordi se reserva el derecho de ampliar este plazo en casos de alta complejidad técnica, notificando al cliente oportunamente.
2. PRESUPUESTO Y AUTORIZACIÓN DE REPARACIÓN: Una vez concluido el diagnóstico, Bionordi emitirá un presupuesto detallado que será comunicado al cliente por escrito o por los medios de contacto registrados. El cliente contará con un plazo de 5 días hábiles a partir de la notificación para aprobar o rechazar dicho presupuesto. La falta de respuesta dentro de este plazo se interpretará como rechazo del presupuesto, aplicándose el cobro de diagnóstico indicado en la cláusula anterior. Ninguna reparación será iniciada sin la autorización expresa del cliente. Bionordi no se responsabiliza por demoras atribuibles a la falta de respuesta oportuna por parte del cliente.
3. GARANTÍA DEL SERVICIO: Las reparaciones realizadas por Bionordi S.A. de C.V. cuentan con una garantía de 12 meses a partir de la fecha de entrega del equipo, la cual cubre exclusivamente la falla o defecto reparado originalmente. Esta garantía quedará sin efecto en los siguientes casos: Manipulación o intervention del equipo por parte de terceros no autorizados por Bionordi. Daños ocasionados por uso inadecuado, caídas, golpes, humedad o agentes externos. Fallas derivadas de mantenimiento insuficiente o negligente por parte del cliente. Daños en componentes distintos al que fue objeto de la reparación original. Para hacer válida la garantía, el cliente deberá presentar el presente documento como comprobante de servicio.
4. PRIVACIDAD Y CONFIDENCIALIDAD: Bionordi S.A. de C.V. se compromete a tratar los datos personales del cliente conforme a lo establecido en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP). Los datos recabados en este documento serán utilizados exclusivamente para la gestión del servicio y comunicaciones relacionadas con el mismo.`;
